//! Type-erased view over metrics, used for dynamic dispatch from the
//! registry without the exporter knowing any crate's concrete metrics type.

use core::fmt;

use crate::counter::Counter;
use crate::value::Value;

/// Object-safe view over a labeled counter collection ([`crate::vec::CounterVec`]).
pub trait ErasedCounterVec: Sync {
    /// Number of distinct label-value combinations currently recorded.
    fn series_count(&self) -> usize;
    /// Write the label block (e.g. `reason="timeout"`, no braces) for series `s`.
    fn write_labels(&self, s: usize, out: &mut dyn fmt::Write) -> fmt::Result;
    /// The current value of series `s`.
    fn value(&self, s: usize) -> u64;
}

/// Object-safe view over a labeled gauge collection ([`crate::vec::GaugeVec`]).
pub trait ErasedGaugeVec: Sync {
    /// Number of distinct label-value combinations currently recorded.
    fn series_count(&self) -> usize;
    /// Write the label block for series `s`.
    fn write_labels(&self, s: usize, out: &mut dyn fmt::Write) -> fmt::Result;
    /// The current value of series `s`.
    fn value(&self, s: usize) -> Value;
}

/// Object-safe view over an unlabeled histogram
/// ([`crate::histogram::IntHistogram`] or [`crate::histogram::Histogram`]).
pub trait ErasedHistogram: Sync {
    /// Number of finite buckets (excludes the implicit `+Inf` bucket).
    fn bucket_count(&self) -> usize;
    /// The upper bound of finite bucket `b`. Bounds must be strictly
    /// increasing; floating-point bounds must also be finite.
    fn bound(&self, b: usize) -> Value;
    /// The non-cumulative count for finite bucket `b`.
    fn bucket(&self, b: usize) -> u64;
    /// Total number of observations (equal to the cumulative `+Inf` bucket).
    fn total_count(&self) -> u64;
    /// Sum of all observed values.
    fn sum(&self) -> Value;
    /// Copy one coherent bucket/sum/count snapshot into `buckets`.
    ///
    /// The renderer passes at least [`Self::bucket_count`] entries and uses
    /// only that prefix. Implementations must prevent an observation from
    /// interleaving with the copy.
    #[cfg(feature = "consistent-histograms")]
    fn snapshot(&self, buckets: &mut [u64]) -> (Value, u64);
}

/// Object-safe view over a labeled histogram collection
/// ([`crate::vec::IntHistogramVec`] or [`crate::vec::HistogramVec`]).
pub trait ErasedHistogramVec: Sync {
    /// Number of finite buckets (excludes the implicit `+Inf` bucket).
    fn bucket_count(&self) -> usize;
    /// The upper bound of finite bucket `b`, shared by every series. Bounds
    /// must be strictly increasing; floating-point bounds must also be finite.
    fn bound(&self, b: usize) -> Value;
    /// Number of distinct label-value combinations currently recorded.
    fn series_count(&self) -> usize;
    /// Write the label block for series `s` (without the `le` label).
    fn write_labels(&self, s: usize, out: &mut dyn fmt::Write) -> fmt::Result;
    /// The non-cumulative count for finite bucket `b` of series `s`.
    fn bucket(&self, s: usize, b: usize) -> u64;
    /// Total number of observations for series `s`.
    fn total_count(&self, s: usize) -> u64;
    /// Sum of all observed values for series `s`.
    fn sum(&self, s: usize) -> Value;
    /// Copy one coherent bucket/sum/count snapshot for series `s` into
    /// `buckets`. See [`ErasedHistogram::snapshot`] for the contract.
    #[cfg(feature = "consistent-histograms")]
    fn snapshot(&self, s: usize, buckets: &mut [u64]) -> (Value, u64);
}

/// A type-erased reference to one metric's data.
pub enum MetricRef<'a> {
    Counter(&'a Counter),
    /// Gauges are read eagerly since they're cheap scalars; no `dyn` needed.
    Gauge(Value),
    Histogram {
        h: &'a dyn ErasedHistogram,
    },
    CounterVec(&'a dyn ErasedCounterVec),
    GaugeVec(&'a dyn ErasedGaugeVec),
    HistogramVec {
        h: &'a dyn ErasedHistogramVec,
    },
}

/// One metric's identity and current data, as produced by a [`MetricGroup`].
pub struct MetricDesc<'a> {
    /// The metric group's namespace, or `""` if none. Prepended to `name` as
    /// `<namespace>_<name>` when rendered.
    pub namespace: &'static str,
    pub name: &'static str,
    pub help: &'static str,
    pub metric: MetricRef<'a>,
}

/// Implemented by the struct generated by [`crate::metrics!`]. Registered
/// with [`crate::register`] and dispatched to dynamically by the renderer, so
/// the exporter never needs to know any crate's concrete metrics type.
pub trait MetricGroup: Sync {
    /// The group's namespace (see [`MetricDesc::namespace`]).
    fn group_name(&self) -> &'static str;
    /// Number of metrics in this group.
    fn len(&self) -> usize;
    /// The metric at `index` (in `0..self.len()`), or `None` if out of range.
    fn get(&self, index: usize) -> Option<MetricDesc<'_>>;

    /// Whether this group has no metrics.
    fn is_empty(&self) -> bool {
        self.len() == 0
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::gauge::Gauge;

    struct FixtureGroup {
        requests: Counter,
        temperature: Gauge,
    }

    impl MetricGroup for FixtureGroup {
        fn group_name(&self) -> &'static str {
            "fixture"
        }

        fn len(&self) -> usize {
            2
        }

        fn get(&self, index: usize) -> Option<MetricDesc<'_>> {
            match index {
                0 => Some(MetricDesc {
                    namespace: "fixture",
                    name: "requests",
                    help: "Total requests.",
                    metric: MetricRef::Counter(&self.requests),
                }),
                1 => Some(MetricDesc {
                    namespace: "fixture",
                    name: "temperature",
                    help: "Current temperature.",
                    metric: MetricRef::Gauge(Value::I64(self.temperature.get())),
                }),
                _ => None,
            }
        }
    }

    #[test]
    fn dynamic_dispatch_over_metric_group() {
        let g = FixtureGroup {
            requests: Counter::new(),
            temperature: Gauge::new(21),
        };
        g.requests.inc_by(3);

        let group: &dyn MetricGroup = &g;
        assert_eq!(group.len(), 2);
        assert!(!group.is_empty());

        let d0 = group.get(0).unwrap();
        assert_eq!(d0.name, "requests");
        match d0.metric {
            MetricRef::Counter(c) => assert_eq!(c.get(), 3),
            _ => panic!("expected Counter"),
        }

        let d1 = group.get(1).unwrap();
        match d1.metric {
            MetricRef::Gauge(Value::I64(v)) => assert_eq!(v, 21),
            _ => panic!("expected Gauge(I64)"),
        }

        assert!(group.get(2).is_none());
    }
}
