#![no_std]
#![forbid(unsafe_code)]

//! Prometheus-style metrics for `no_std` embedded devices, with no heap
//! allocation.
//!
//! # Declaring metrics
//!
//! Each crate/binary declares the metrics it exports with [`metrics!`],
//! which expands to a real struct (one field per metric, so IDE
//! autocomplete and find-usages work at call sites), a global accessor
//! function, and an [`impl MetricGroup`](MetricGroup) for dynamic dispatch.
//!
//! ```
//! embeprom::metrics! {
//!     /// Wi-Fi driver metrics.
//!     pub struct WifiMetrics;
//!     namespace = "wifi";
//!     static METRICS;
//!     fn metrics;
//!
//!     counter        packets_sent            = "Total Wi-Fi frames transmitted.";
//!     gauge          rssi_dbm                = "Last measured RSSI in dBm.";
//!     counter_vec<4> disconnects_total["reason"] = "Disconnects, by reason.";
//!     int_histogram  tx_latency_us[buckets: 100, 500, 1000, 5000]
//!                                            = "TX completion latency in microseconds.";
//! }
//!
//! // Anywhere in the crate, with no collector object to thread through, and
//! // no separate registration step: the first call to `metrics()` registers
//! // `WifiMetrics` with the global registry (see "Registration" below).
//! metrics().packets_sent.inc();
//! metrics().disconnects_total.inc(&["beacon_timeout"]);
//! metrics().tx_latency_us.observe(42);
//! ```
//!
//! # Registration
//!
//! The accessor function generated by [`metrics!`] (`metrics()` above)
//! self-registers its group with the global registry the first time it's
//! called — via [`OnceRegister`], a one-shot guard, so this costs one atomic
//! load on every call after the first and never repeats the registration
//! work. There is no explicit step to wire up in `main()`.
//!
//! This means a metrics group that's declared but never recorded stays
//! absent from scrapes until first touched (it isn't visible at `0` from
//! boot the way an eagerly-registered metric would be). If a group's first
//! recording happens to occur when the global registry is already at
//! capacity (see [`MAX_GROUPS`]), that group's metrics are
//! silently dropped from future scrapes rather than panicking — logged once
//! per group via `log::error!` if the `log` feature is enabled.
//!
//! To register a group eagerly instead (so it's visible at `0` from boot),
//! or to make a full registry a hard startup failure rather than a silent
//! one, call [`register`] explicitly, e.g. in `main()`:
//!
//! ```
//! # embeprom::metrics! {
//! #     pub struct WifiMetrics;
//! #     static METRICS;
//! #     fn metrics;
//! #     counter packets_sent = "Total Wi-Fi frames transmitted.";
//! # }
//! embeprom::register(&METRICS);
//! // or, for several crates at once: embeprom::register_all!(wifi::METRICS, net::METRICS);
//! ```
//!
//! Calling [`register`] for a group that already self-registered (or vice
//! versa) is safe: [`Registry::try_register`] dedups by pointer identity, so
//! a group is never counted twice.
//!
//! The final application can install a smaller caller-owned registry before
//! any metrics are touched. Lazy registration from any dependency will then
//! target it, and [`Renderer::new`] will render it:
//!
//! ```no_run
//! static REGISTRY: embeprom::Registry<8> = embeprom::Registry::new();
//! embeprom::install_registry(&REGISTRY).unwrap();
//! ```
//!
//! A metrics group can instead name a directly visible registry with
//! `metrics! { registry = REGISTRY; ... }`, or use
//! `metrics! { registration = manual; ... }` when it should be registered
//! explicitly with one or more registries.
//!
//! # Exporting
//!
//! [`Renderer`] is a pull-based cursor over every registered group's
//! metrics, rendered into Prometheus text exposition format. It's
//! deliberately synchronous and `no_std` so it has no opinion about how
//! bytes reach the network; the caller drives it, awaiting between lines as
//! needed:
//!
//! ```
//! let mut renderer = embeprom::Renderer::new();
//! while let Some(line) = renderer.next_line().unwrap() {
//!     // send `line.as_bytes()` to whatever sink you have.
//! }
//! ```
//!
//! The default renderer holds one line of at most [`MAX_LINE`] bytes. Select a
//! different bound with `Renderer::with_line_capacity::<512>()`.
//! [`RenderError::LineTooLong`] reports the exact required capacity and is
//! terminal rather than silently omitting part of the exposition.
//! When `consistent-histograms` is enabled, the renderer also holds reusable
//! scratch for [`MAX_HISTOGRAM_BUCKETS`] finite buckets. Tune both bounds with
//! `Renderer::with_capacities::<LINE, HIST_BUCKETS>()`.
//!
//! For a synchronous sink implementing [`core::fmt::Write`], use
//! [`write_all`] instead.
//!
//! ## Serving over HTTP with `picoserve`
//!
//! `embeprom` has no dependency on `picoserve` (or any HTTP server), but its
//! pull-based renderer is a direct match for `picoserve`'s chunked response
//! body: a `Chunks` implementation writes one rendered line per HTTP chunk
//! and awaits between lines.
//!
//! ```ignore
//! use picoserve::response::chunked::{ChunkWriter, Chunks, ChunksWritten};
//!
//! struct MetricsResponse;
//!
//! impl Chunks for MetricsResponse {
//!     fn content_type(&self) -> &'static str {
//!         embeprom::CONTENT_TYPE
//!     }
//!
//!     async fn write_chunks<W: picoserve::io::Write>(
//!         self,
//!         mut chunk_writer: ChunkWriter<W>,
//!     ) -> Result<ChunksWritten, W::Error> {
//!         let mut renderer = embeprom::Renderer::new();
//!         while let Some(line) = renderer
//!             .next_line()
//!             .expect("increase the Renderer line capacity")
//!         {
//!             chunk_writer.write_chunk(line.as_bytes()).await?;
//!         }
//!         chunk_writer.finalize().await
//!     }
//! }
//!
//! // route:
//! // picoserve::routing::get(|| async {
//! //     picoserve::response::chunked::ChunkedResponse::new(MetricsResponse)
//! // })
//! ```
//!
//! [`Content`](https://docs.rs/picoserve/latest/picoserve/response/trait.Content.html)
//! (picoserve's fixed-length response body trait) is deliberately not used
//! here: it requires knowing the total body length up front, which would
//! force a full discarded render pass first (see [`rendered_len`], which
//! exists for exactly that but is documented as a last resort) and can go
//! stale between that pass and the real one since metrics are live atomics.
//!
//! # Labeled metrics and cardinality
//!
//! [`CounterVec`], [`GaugeVec`], [`IntHistogramVec`] (and, with the `float`
//! feature, [`HistogramVec`]) each declare a maximum number of distinct
//! label-value combinations via a const generic (e.g. `CounterVec<4>` for up
//! to 4 series). Once that capacity is exhausted, newly observed label
//! combinations are silently routed to unrendered sink handles whose updates
//! are no-ops, while existing series keep updating normally. Oversized
//! rendered label blocks use the same sink behavior.
//!
//! For stable label values, call `with` once during initialization and retain
//! its series handle. Updating that handle accesses the metric storage
//! directly, avoiding repeated label construction and label-map lookup. The
//! convenience methods that accept label values perform a lookup on every
//! call and are best reserved for dynamic or infrequent labels.

mod config;
mod counter;
mod erased;
mod escape;
mod gauge;
mod histogram;
mod labels;
mod macros;
mod registry;
mod render;
mod value;
mod vec;

pub use counter::Counter;
pub use config::{LABEL_VALUE_LEN, MAX_GROUPS, MAX_HISTOGRAM_BUCKETS, MAX_LINE};
pub use erased::{ErasedCounterVec, ErasedGaugeVec, ErasedHistogram, ErasedHistogramVec, MetricDesc, MetricGroup, MetricRef};
pub use escape::{valid_label_name, valid_metric_name};
pub use gauge::Gauge;
pub use histogram::IntHistogram;
pub use registry::{
    group_count, install_registry, register, snapshot, try_register, GroupSnapshot,
    InstallRegistryError, OnceRegister, Registry, RegistryFull,
};
pub use render::{rendered_len, write_all, RenderError, Renderer, CONTENT_TYPE};
pub use value::Value;
pub use vec::{
    CounterSeries, CounterVec, GaugeSeries, GaugeVec, IntHistSeries, IntHistogramVec,
};

#[cfg(feature = "float")]
pub use gauge::GaugeF64;
#[cfg(feature = "float")]
pub use histogram::Histogram;
#[cfg(feature = "float")]
pub use vec::{HistSeries, HistogramVec};
