//! The central metrics registry: a fixed-capacity list of registered
//! [`MetricGroup`]s. Groups can be added explicitly via [`register`], or
//! self-register lazily on first access via [`OnceRegister`] (used by the
//! accessor function generated by [`crate::metrics!`]).

use core::cell::RefCell;

use critical_section::Mutex;
use heapless::Vec;
use portable_atomic::{AtomicU8, Ordering};

use crate::erased::MetricGroup;

fn same_group(a: &dyn MetricGroup, b: &dyn MetricGroup) -> bool {
    match (core::mem::size_of_val(a), core::mem::size_of_val(b)) {
        // Distinct zero-sized statics may legally have the same data address.
        // Their concrete type is the only stable identity that also survives
        // duplicated vtables across codegen units.
        (0, 0) => a.type_id() == b.type_id(),
        // A zero-sized static may also share an address with an unrelated
        // allocation, so data-address equality is not meaningful here.
        (0, _) | (_, 0) => false,
        _ => core::ptr::addr_eq(a, b),
    }
}

/// Returned by [`Registry::register`] when the registry is already at
/// capacity `N`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct RegistryFull;

/// A snapshot of the groups registered with a [`Registry`] at a point in time.
pub type GroupSnapshot<const N: usize = { crate::config::MAX_GROUPS }> =
    Vec<&'static dyn MetricGroup, N>;

/// A fixed-capacity registry of metric groups, holding at most `N` groups.
pub struct Registry<const N: usize = { crate::config::MAX_GROUPS }> {
    groups: Mutex<RefCell<Vec<&'static dyn MetricGroup, N>>>,
}

impl<const N: usize> Registry<N> {
    /// Create an empty registry.
    pub const fn new() -> Self {
        Self {
            groups: Mutex::new(RefCell::new(Vec::new())),
        }
    }

    /// Register a metric group. Registering the same group (by static
    /// identity) more than once is a no-op, so explicit [`register`] calls can
    /// coexist with a group that also self-registers via [`OnceRegister`].
    ///
    /// # Errors
    ///
    /// Returns [`RegistryFull`] if the registry already contains `N`
    /// distinct groups.
    pub fn register(&self, group: &'static dyn MetricGroup) -> Result<(), RegistryFull> {
        critical_section::with(|cs| {
            let mut groups = self.groups.borrow_ref_mut(cs);
            if groups.iter().any(|g| same_group(*g, group)) {
                return Ok(());
            }
            groups.push(group).map_err(|_| RegistryFull)
        })
    }

    /// Copy out the currently registered groups.
    pub fn snapshot(&self) -> Vec<&'static dyn MetricGroup, N> {
        critical_section::with(|cs| self.groups.borrow_ref(cs).clone())
    }
}

impl<const N: usize> Default for Registry<N> {
    fn default() -> Self {
        Self::new()
    }
}

// Keep the singleton private so all global access goes through the small
// registration and snapshot API. Caller-owned registries are ordinary
// `Registry<N>` statics and can be rendered directly.
static GLOBAL: Registry = Registry::new();

/// Register a metric group with the global registry.
///
/// Call this once per crate/library at startup, e.g.:
///
/// ```
/// # mod metrics {
/// #     embeprom::metrics! {
/// #         /// Total requests.
/// #         requests: Counter,
/// #     }
/// # }
/// embeprom::register(&metrics::METRICS).unwrap();
/// ```
///
/// Metrics groups declared with [`crate::metrics!`] self-register on first
/// access (see [`OnceRegister`]), so calling this explicitly is optional for
/// them. Explicit registration makes every metric visible from boot and lets
/// startup code decide how to handle insufficient registry capacity.
///
/// # Errors
///
/// Returns [`RegistryFull`] if the global registry is already at capacity.
pub fn register(group: &'static dyn MetricGroup) -> Result<(), RegistryFull> {
    GLOBAL.register(group)
}

/// Copy out the groups currently registered with the global registry.
pub fn snapshot() -> GroupSnapshot {
    GLOBAL.snapshot()
}

const UNREGISTERED: u8 = 0;
const REGISTERING: u8 = 1;
const REGISTERED: u8 = 2;

/// A one-shot guard that registers a metric group with the global registry
/// on the first call to [`ensure`](Self::ensure), and does nothing on every
/// subsequent call. Used by the accessor function generated by
/// [`crate::metrics!`] so that recording a metric for the first time
/// self-registers its group, with no explicit `main()`-side call needed.
///
/// The uncontended one-time cost is a single [`register`] call; every
/// later call is one `Acquire` load of an atomic state. A caller concurrent
/// with the first registration may repeat the deduplicated registration
/// attempt so it never returns while the group is still absent. If the
/// registry is full, the failure is reported at most once per `OnceRegister`
/// (i.e. at most once per metrics group, not once per metric write) via a
/// `log::error!` when the `log` feature is enabled, and silently otherwise —
/// either way, the group's metrics are simply absent from the render output
/// rather than causing a panic deep in a hot path.
pub struct OnceRegister {
    state: AtomicU8,
}

impl OnceRegister {
    /// Create a new, not-yet-registered guard.
    pub const fn new() -> Self {
        Self {
            state: AtomicU8::new(UNREGISTERED),
        }
    }

    /// Register `group` with the global registry if this is the first call;
    /// a no-op on every later call.
    pub fn ensure(&self, group: &'static dyn MetricGroup) {
        self.ensure_with(group, || register(group));
    }

    /// Register `group` with `registry` if this is the first call; a no-op on
    /// every later call. This is used by `metrics! { registry = REGISTRY; ... }`
    /// to retain register-on-first-use with a caller-owned registry.
    pub fn ensure_in<const N: usize>(
        &self,
        registry: &Registry<N>,
        group: &'static dyn MetricGroup,
    ) {
        self.ensure_with(group, || registry.register(group));
    }

    fn ensure_with(
        &self,
        group: &'static dyn MetricGroup,
        register: impl FnOnce() -> Result<(), RegistryFull>,
    ) {
        if self.state.load(Ordering::Acquire) == REGISTERED {
            return;
        }

        let leader = match self.state.compare_exchange(
            UNREGISTERED,
            REGISTERING,
            Ordering::AcqRel,
            Ordering::Acquire,
        ) {
            Ok(_) => true,
            Err(REGISTERED) => return,
            Err(REGISTERING) => false,
            Err(_) => unreachable!("embeprom: invalid registration state"),
        };

        // A concurrent caller that observes REGISTERING must not return before
        // registration has happened. Repeating the attempt is safe because
        // Registry::register deduplicates the group, and unlike spinning,
        // this cannot deadlock when the caller is an interrupt handler that
        // preempted the first caller.
        let result = register();
        if leader {
            self.state.store(REGISTERED, Ordering::Release);
            #[cfg(feature = "log")]
            if result.is_err() {
                log::error!(
                    "embeprom: metric group \"{}\" did not self-register: registry is full \
                     (increase its capacity); its metrics will be absent from scrapes",
                    group.group_name()
                );
            }
        }

        #[cfg(not(feature = "log"))]
        let _ = (group, result);
    }
}

impl Default for OnceRegister {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    struct EmptyGroup(&'static str);

    struct ZeroSizedA;
    struct ZeroSizedB;

    impl MetricGroup for EmptyGroup {
        fn group_name(&self) -> &'static str {
            self.0
        }
        fn len(&self) -> usize {
            0
        }
        fn get(&self, _index: usize) -> Option<crate::erased::MetricDesc<'_>> {
            None
        }
    }

    impl MetricGroup for ZeroSizedA {
        fn group_name(&self) -> &'static str {
            "zero_a"
        }
        fn len(&self) -> usize {
            0
        }
        fn get(&self, _index: usize) -> Option<crate::erased::MetricDesc<'_>> {
            None
        }
    }

    impl MetricGroup for ZeroSizedB {
        fn group_name(&self) -> &'static str {
            "zero_b"
        }
        fn len(&self) -> usize {
            0
        }
        fn get(&self, _index: usize) -> Option<crate::erased::MetricDesc<'_>> {
            None
        }
    }

    static A: EmptyGroup = EmptyGroup("a");
    static B: EmptyGroup = EmptyGroup("b");
    static C: EmptyGroup = EmptyGroup("c");
    static D: EmptyGroup = EmptyGroup("d");
    static ZERO_SIZED_A: ZeroSizedA = ZeroSizedA;
    static ZERO_SIZED_B: ZeroSizedB = ZeroSizedB;

    #[test]
    fn registers_and_snapshots() {
        let r: Registry<2> = Registry::new();
        assert!(r.snapshot().is_empty());

        r.register(&A).unwrap();
        r.register(&B).unwrap();

        let snap = r.snapshot();
        assert_eq!(snap.len(), 2);
        assert_eq!(snap[0].group_name(), "a");
        assert_eq!(snap[1].group_name(), "b");
    }

    #[test]
    fn register_reports_full() {
        let r: Registry<1> = Registry::new();
        assert_eq!(r.register(&A), Ok(()));
        assert_eq!(r.register(&B), Err(RegistryFull));
        assert_eq!(r.snapshot().len(), 1);
    }

    #[test]
    fn registering_the_same_group_twice_is_a_no_op() {
        let r: Registry<1> = Registry::new();
        assert_eq!(r.register(&A), Ok(()));
        assert_eq!(r.register(&A), Ok(()));
        assert_eq!(r.snapshot().len(), 1);
    }

    #[test]
    fn distinct_zero_sized_group_types_register_independently() {
        let r: Registry<2> = Registry::new();
        assert_eq!(r.register(&ZERO_SIZED_A), Ok(()));
        assert_eq!(r.register(&ZERO_SIZED_B), Ok(()));
        assert_eq!(r.snapshot().len(), 2);
    }

    #[test]
    fn global_registry_accepts_registration() {
        register(&C).unwrap();
        assert_eq!(
            snapshot()
                .iter()
                .filter(|g| core::ptr::addr_eq(**g, &raw const C))
                .count(),
            1
        );
    }

    #[test]
    fn once_register_registers_exactly_once() {
        let once = OnceRegister::new();

        once.ensure(&D);
        once.ensure(&D);
        once.ensure(&D);
        assert_eq!(
            snapshot()
                .iter()
                .filter(|g| core::ptr::addr_eq(**g, &raw const D))
                .count(),
            1
        );
    }

    #[test]
    fn once_register_can_target_a_caller_owned_registry() {
        let registry: Registry<1> = Registry::new();
        let once = OnceRegister::new();

        once.ensure_in(&registry, &A);
        once.ensure_in(&registry, &A);
        assert_eq!(registry.snapshot().len(), 1);
    }

    #[test]
    fn concurrent_first_use_never_returns_without_attempting_registration() {
        let once = OnceRegister::new();
        once.state.store(REGISTERING, Ordering::Release);
        let attempted = core::cell::Cell::new(false);

        once.ensure_with(&A, || {
            attempted.set(true);
            Ok(())
        });

        assert!(attempted.get());
    }
}
